### PR TITLE
revert contatenation feature that broke code samples with terminating…

### PR DESCRIPTION
**Pull request by sandlerr**
… slashes

cc @zendesk/vegemite @zendesk/wombat @chucknado

### CODE REVIEW

**Comment by sandlerr** [comment]
@grosser would you mind bumping a release?

**Comment by sandlerr** [comment]
I've released to git, just need someone to push to rubygems

**Comment by grosser** [comment]
gimme your rubygems email

**Comment by grosser** [comment]
added you

**Comment by sandlerr** [comment]
Thanks!

**Pull request merged**
